// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260207183631_InitialEstoque")]
    partial class InitialEstoque
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Estoque.Aggregates.ItemEstoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("itens_estoque", (string)null);
                });

            modelBuilder.Entity("Domain.Estoque.Aggregates.ItemEstoque", b =>
                {
                    b.OwnsOne("Domain.Estoque.ValueObjects.ItemEstoque.Nome", "Nome", b1 =>
                        {
                            b1.Property<Guid>("ItemEstoqueId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("nome");

                            b1.HasKey("ItemEstoqueId");

                            b1.ToTable("itens_estoque");

                            b1.WithOwner()
                                .HasForeignKey("ItemEstoqueId");
                        });

                    b.OwnsOne("Domain.Estoque.ValueObjects.ItemEstoque.PrecoItem", "Preco", b1 =>
                        {
                            b1.Property<Guid>("ItemEstoqueId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("preco");

                            b1.HasKey("ItemEstoqueId");

                            b1.ToTable("itens_estoque");

                            b1.WithOwner()
                                .HasForeignKey("ItemEstoqueId");
                        });

                    b.OwnsOne("Domain.Estoque.ValueObjects.ItemEstoque.Quantidade", "Quantidade", b1 =>
                        {
                            b1.Property<Guid>("ItemEstoqueId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Valor")
                                .HasColumnType("integer")
                                .HasColumnName("quantidade");

                            b1.HasKey("ItemEstoqueId");

                            b1.ToTable("itens_estoque");

                            b1.WithOwner()
                                .HasForeignKey("ItemEstoqueId");
                        });

                    b.OwnsOne("Domain.Estoque.ValueObjects.ItemEstoque.TipoItemEstoque", "TipoItemEstoque", b1 =>
                        {
                            b1.Property<Guid>("ItemEstoqueId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("tipo_item_estoque");

                            b1.HasKey("ItemEstoqueId");

                            b1.ToTable("itens_estoque");

                            b1.WithOwner()
                                .HasForeignKey("ItemEstoqueId");
                        });

                    b.Navigation("Nome")
                        .IsRequired();

                    b.Navigation("Preco")
                        .IsRequired();

                    b.Navigation("Quantidade")
                        .IsRequired();

                    b.Navigation("TipoItemEstoque")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
